name: pingolearn
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  firebase_remote_config: ^5.0.3
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  google_fonts: ^6.2.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
